services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pm_validator
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: 1234@Qwer
    volumes:
      - minio_data:/data
    ports:
      - "9010:9000"
      - "9011:9001"
    command: server /data --console-address ":9001"

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/pm_validator
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: 1234@Qwer
      MINIO_BUCKET: pm-photos
      LLM_URL: http://10.130.154.133:8000/v1/chat/completions
      SECRET_KEY: production-secret-key-change-me
      ALGORITHM: HS256
    ports:
      - "8002:8001"
    depends_on:
      - db
      - minio

  frontend:
    build: ./frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8002
      NEXT_PUBLIC_MINIO_URL: http://localhost:9010/pm-photos
    ports:
      - "3001:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
  minio_data:
